### ISSUE TITLE
Incorrect use in exercise 1.4

### ISSUE THREAD

**Issue by virt87** [careercup/CtCI-6th-Edition#26] opened 2015-10-28 05:13 UTC
A c++ code with use of a java code is in use without any conversion.
The important part of getting the table of frequency hasn't been implemented.
This looks very strange
```		
std::vector<int> table = Common::buildCharFrequencyTable(phrase);
```
as soon as Coomon is a java file

**Comment by asaph** [comment] 2016-02-18 06:46
This looks like a duplicate of #27 which was merged to master.

**Closed by asaph** 2016-02-18 06:46 UTC
